/*
 * ultrasonic.h
 *
 *  Created on: Oct 9, 2024
 *      Author: Manar
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "gpio.h"
#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

/* Ultrasonic Port Configurations */
#define ULTRASONIIC_ECHO_PORT_ID          PORTD_ID
#define ULTRASONIIC_ECHO_PIN_ID           PIN6_ID

#define ULTRASONIIC_TRIGGER_PORT_ID       PORTD_ID
#define ULTRASONIIC_TRIGGER_PIN_ID        PIN7_ID

/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ICU driver as required.
 * Set up the ICU callback function.
 * Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Send the trigger pulse by using the Ultrasonic_Trigger function.
 * Start the measurement process via the ICU driver.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
