/*
 * ultrasonic.c
 *
 *  Created on: Oct 9, 2024
 *      Author: Manar
 */

#include "ultrasonic.h"
#include "icu.h"
#include <util/delay.h>

/*******************************************************************************
 *                         Global Variables                                    *
 *******************************************************************************/
uint16 g_timeHigh = 0;
uint8 g_edgeCount = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ICU driver as required.
 * Set up the ICU callback function.
 * Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	ICU_ConfigType ICU_Configurations = {F_CPU_8, RAISING};
	ICU_init(&ICU_Configurations);
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	GPIO_setupPinDirection(ULTRASONIIC_ECHO_PORT_ID, ULTRASONIIC_ECHO_PIN_ID, PIN_INPUT);
	GPIO_setupPinDirection(ULTRASONIIC_TRIGGER_PORT_ID, ULTRASONIIC_TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description :
 * Send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIIC_TRIGGER_PORT_ID, ULTRASONIIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIIC_TRIGGER_PORT_ID, ULTRASONIIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description :
 * Send the trigger pulse by using the Ultrasonic_Trigger function.
 * Start the measurement process via the ICU driver.
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();
	while(g_edgeCount < 2);
	g_edgeCount = 0;
	ICU_clearTimerValue();
	return g_timeHigh / 117 + 1;
}

/*
 * Description :
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		g_timeHigh = ICU_getInputCaptureValue();
		ICU_setEdgeDetectionType(RAISING);
	}
}

